### ISSUE TITLE
Improve the register transaction logic to use SQL Transaction

### ISSUE THREAD

**Issue by roam9152** [RoiJS/Beelina#47]
Right now, we are running the SQL insert and updates regarding register order transaction logic in a separate session which can be problematic if any of the transaction fails while the previous transaction already committed to the database. To avoid this kind of scenario, we will take advantage of the SQL transaction built in with EF Core.

**Comment by RoiJS** [comment]
Turned out that the other logic for registering order transaction is now obsolete. In fact, there is no need to enhanced on the logic and no need to use SQL transaction. I now removed all obsolete code.
